<a href="https://colab.research.google.com/github/VishruthaGopa/AI-Product-Review-Analyzer/blob/master/TrainModel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
!git clone https://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@github.com/VishruthaGopa/AI-Product-Review-Analyzer.git

fatal: destination path 'AI-Product-Review-Analyzer' already exists and is not an empty directory.

In [25]:
import argparse
import os
import sys
import pandas as pd
import torch
import numpy as np
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer,
    DataCollatorWithPadding
)
from datasets import Dataset
from sklearn.model_selection import KFold, StratifiedKFold
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import train_test_split

# Disable tokenizer parallel processing to prevent potential conflicts with multi-process training
os.environ["TOKENIZERS_PARALLELISM"] = "false"

class ABSAKFoldTrainer:
    def __init__(self, model_name="yangheng/deberta-v3-base-absa-v1.1"):

        # Initialize the ABSA trainer with K-Fold CV
        print(f"Loading base model: {model_name}")

        # Using standard tokenizer
        self.tokenizer = AutoTokenizer.from_pretrained(model_name)
        self.base_model_name = model_name

        # Define label mapping

        # Map sentiment labels to numeric IDs for model training
        self.label2id = {"negative": 0, "neutral": 1, "positive": 2}
        # Create reverse mapping to interpret predictions back to human-readable labels
        self.id2label = {v: k for k, v in self.label2id.items()}

        print(f"Base model loaded")

    def load_dataset(self, csv_path):
        # Load dataset from CSV file
        print(f"Loading dataset from: {csv_path}")

        df = pd.read_csv(csv_path)

        # Format data
        df['text'] = df['text'].astype(str)
        df['aspect'] = df['aspect'].astype(str)
        df['sentiment'] = df['sentiment'].str.lower()

        # Map sentiments to IDs
        df['label'] = df['sentiment'].map(self.label2id)

        # Remove rows with NaN labels
        df = df.dropna(subset=['label'])
        # Type cast as int
        df['label'] = df['label'].astype(int)

        # gets sentiment distribution
        print(f"Loaded {len(df)} samples")
        print(f"Sentiment distribution:")
        for sentiment, label_id in self.label2id.items():
            count = (df['label'] == label_id).sum()
            percentage = (count / len(df)) * 100
            print(f"   {sentiment}: {count} ({percentage:.1f}%)")

        return df

    def preprocess_data(self, df):
        # Preprocess dataset for model training

        # Convert each column to list
        texts = df['text'].tolist()
        aspects = df['aspect'].tolist()
        labels = df['label'].tolist()

        # Tokenize
        encodings = self.tokenizer(
            texts,              # List of text sentences
            aspects,            # List of aspects to analyze
            truncation=True,    # Cut off text longer than 512 tokens
            padding=True,       # Add padding to make all inputs same length
            max_length=512,     # Maximum length allowed
            return_tensors='pt' # Return as PyTorch tensors
        )

        return {
            'input_ids': encodings['input_ids'], # The token IDs (text as numbers)
            'attention_mask': encodings['attention_mask'], # Which tokens to pay attention to, not the padding
            'labels': torch.tensor(labels, dtype=torch.long) # Convert labels to proper tensor format
        }


    def compute_metrics(self, eval_pred):
        # Compute metrics for evaluation

        predictions, labels = eval_pred
        # [prob neg, prob neutral, prob positive] #TODO: confirm
        predictions = np.argmax(predictions, axis=1)

        accuracy = accuracy_score(labels, predictions)
        f1 = f1_score(labels, predictions, average='macro')
        precision = precision_score(labels, predictions, average='macro', zero_division=0)
        recall = recall_score(labels, predictions, average='macro', zero_division=0)

        return {
            'accuracy': accuracy,
            'f1': f1,
            'precision': precision,
            'recall': recall
        }

    def train_fold(self, train_df, val_df, fold_num, output_dir, epochs=5, batch_size=8, learning_rate=0.00005):
        # Train a single fold

        print(f"\n Training Fold {fold_num + 1}")
        print("-" * 40)

        # Create new untrained model for this fold and set up label mappings
        model = AutoModelForSequenceClassification.from_pretrained(self.base_model_name)
        model.config.id2label = self.id2label
        model.config.label2id = self.label2id

        # Preprocess data
        train_encodings = self.preprocess_data(train_df) # Convert text to numbers
        val_encodings = self.preprocess_data(val_df)

        train_dataset = Dataset.from_dict(train_encodings)
        val_dataset = Dataset.from_dict(val_encodings)

        # Data collator makes sure all examples in a batch have same length,
        data_collator = DataCollatorWithPadding(tokenizer=self.tokenizer)

        # Create output directory for each fold
        fold_output_dir = os.path.join(output_dir, f"fold_{fold_num + 1}")

        # Training arguments
        training_args = TrainingArguments(
            output_dir=fold_output_dir,
            num_train_epochs=epochs,
            per_device_train_batch_size=batch_size,
            per_device_eval_batch_size=batch_size * 2,
            learning_rate=learning_rate,
            warmup_ratio=0.1,# gradually increase learning rate at start
            weight_decay=0.01,# penalty to prevent overcomplicated models
            save_strategy="no",  # Don't save checkpoints during training
            eval_strategy="epoch",
            save_total_limit=0,
            load_best_model_at_end=False,
            metric_for_best_model="accuracy",
            greater_is_better=True,
            report_to=None,
        )

        # Initialize trainer
        trainer = Trainer(
            model=model,
            args=training_args,
            train_dataset=train_dataset,
            eval_dataset=val_dataset,
            tokenizer=self.tokenizer,
            data_collator=data_collator,
            compute_metrics=self.compute_metrics,
        )

        # Train
        print(f"   Training samples: {len(train_df)}")
        print(f"   Validation samples: {len(val_df)}")

        train_result = trainer.train()

        # Save the fold model as a single .pth file
        fold_model_path = os.path.join(output_dir, f"fold_{fold_num + 1}.pth")
        torch.save({
            'model_state_dict': model.state_dict(),
            'config': model.config,
            'label2id': self.label2id,
            'id2label': self.id2label,
            'fold_num': fold_num + 1,
            'train_loss': train_result.metrics['train_loss']
        }, fold_model_path)
        print(f"   Saved fold model to: {fold_model_path}")

        # Evaluate on validation set
        eval_results = trainer.evaluate()

        return {
            'fold': fold_num + 1,
            'train_loss': train_result.metrics['train_loss'],
            'eval_loss': eval_results['eval_loss'],
            'accuracy': eval_results['eval_accuracy'],
            'f1': eval_results['eval_f1'],
            'precision': eval_results['eval_precision'],
            'recall': eval_results['eval_recall'],
            'model': model  # Return the model object
        }

    def cross_validate(self, df, k=5, output_dir="kfold_models", epochs=5, batch_size=8, learning_rate=0.00005, random_state=42):
        #Perform K-Fold cross-validation

        print(f"\n Starting {k}-Fold Cross Validation")
        print("=" * 60)

        # Create output directory
        os.makedirs(output_dir, exist_ok=True)

        # Initialize K-Fold (use StratifiedKFold for imbalanced classes)
        kf = StratifiedKFold(n_splits=k, shuffle=True, random_state=random_state) # random_state: Set fixed random seed for reproducible data splits

        fold_results = []
        models = []  # Store model objects to find the best one

        # Perform K-Fold Cross Validation
        for fold_num, (train_idx, val_idx) in enumerate(kf.split(df, df['label'])):
            # Split data
            train_df = df.iloc[train_idx].reset_index(drop=True)
            val_df = df.iloc[val_idx].reset_index(drop=True)

            # Train this fold
            fold_result = self.train_fold(
                train_df=train_df,
                val_df=val_df,
                fold_num=fold_num,
                output_dir=output_dir,
                epochs=epochs,
                batch_size=batch_size,
                learning_rate=learning_rate
            )

            # Store model
            models.append(fold_result['model'])
            # Remove model from results dict
            del fold_result['model']

            fold_results.append(fold_result)

            # Print fold results
            print(f"\n Fold {fold_num + 1} Results:")
            for key, value in fold_result.items():
                if key != 'fold':
                    print(f"   {key}: {value:.4f}")

        # Calculate overall statistics
        print("\n" + "=" * 60)
        print(">> CROSS-VALIDATION RESULTS >>")
        print("=" * 60)

        # Convert results to DataFrame
        results_df = pd.DataFrame(fold_results)

        # Print fold-wise results
        print("\nFold-wise Performance:")
        print(results_df.to_string(index=False))

        # Calculate mean and std
        metrics = ['accuracy', 'f1', 'precision', 'recall', 'train_loss', 'eval_loss']

        print("\nOverall Statistics:")
        print("-" * 40)
        for metric in metrics:
            mean_val = results_df[metric].mean()
            std_val = results_df[metric].std()
            print(f"{metric.capitalize():12} : {mean_val:.4f} (±{std_val:.4f})")

        # Save results to CSV
        results_df.to_csv(os.path.join(output_dir, "cv_results.csv"), index=False)

        # Save the best model as a single .pth file
        self.save_best_model_single_file(results_df, models, output_dir)

        return results_df

    def save_best_model_single_file(self, results_df, models, output_dir):
        """Save the best model as a single .pth file"""
        print(f"\nSaving results to: {output_dir}/cv_results.csv")

        # Find the best fold based on validation accuracy
        best_fold_idx = results_df['accuracy'].idxmax()
        best_fold_num = int(results_df.loc[best_fold_idx, 'fold'])
        best_model = models[best_fold_idx]

        print(f"\nBest performing fold: {best_fold_num}")
        print(f"   Accuracy: {results_df.loc[best_fold_idx, 'accuracy']:.4f}")
        print(f"   F1-Score: {results_df.loc[best_fold_idx, 'f1']:.4f}")

        # Save the best model as a single .pth file
        best_model_path = os.path.join(output_dir, "best_model.pth")
        torch.save({
            'model_state_dict': best_model.state_dict(),
            'config': best_model.config,
            'label2id': self.label2id,
            'id2label': self.id2label,
            'tokenizer': self.tokenizer,  # Save tokenizer configuration
            'fold_num': best_fold_num,
            'accuracy': results_df.loc[best_fold_idx, 'accuracy'],
            'f1': results_df.loc[best_fold_idx, 'f1']
        }, best_model_path)

        print(f"\nBest model saved as single file: {best_model_path}")
        print(f"File size: {os.path.getsize(best_model_path) / (1024*1024):.2f} MB")

    def final_test(self, test_df, model_path):
        """Test the best model loaded from a single .pth file"""

        print(f"\nFinal Testing on Separate Test Set")
        print("=" * 50)

        # Load the model from single .pth file
        print(f"Loading model from: {model_path}")
        checkpoint = torch.load(model_path, map_location='cpu')

        # Recreate the model architecture
        model = AutoModelForSequenceClassification.from_pretrained(
            self.base_model_name,
            num_labels=len(self.label2id)
        )

        # Load the state dict
        model.load_state_dict(checkpoint['model_state_dict'])
        model.eval()

        # Use saved tokenizer or fallback to base tokenizer
        tokenizer = checkpoint.get('tokenizer', self.tokenizer)

        predictions = []
        true_labels = []

        for _, row in test_df.iterrows():
            # Tokenize the review text and aspect
            inputs = tokenizer(
                row['text'],
                row['aspect'],
                return_tensors="pt",
                truncation=True,
                max_length=512
            )

            with torch.no_grad(): # Turn off learning (just testing)
                outputs = model(**inputs) # pass elements in dictionary as separate arguments
                pred_probs = torch.nn.functional.softmax(outputs.logits, dim=-1) #get model predictions probabilities
                predicted_class = torch.argmax(pred_probs, dim=1).item()

            predictions.append(predicted_class)
            true_labels.append(self.label2id[row['sentiment'].lower()])

        # Calculate metrics
        accuracy = accuracy_score(true_labels, predictions)
        f1 = f1_score(true_labels, predictions, average='weighted')

        print(f"Test Set Performance:")
        print(f"   Accuracy: {accuracy:.4f}")
        print(f"   F1-Score: {f1:.4f}")
        print(f"   Test Samples: {len(test_df)}")

        return accuracy, f1

In [26]:
def main():
    # ============================
    # MANUAL PARAMETER SETTINGS
    # ============================
    data_path = "/content/AI-Product-Review-Analyzer/train_dataset.csv"
    k_folds = 5
    output_dir = "kfold_models"
    epochs = 5
    batch_size = 8
    learning_rate = 5e-5
    test_split = 0.2

    print("ABSA Model K-Fold Cross Validation")
    print("=" * 60)

    try:
        # Initialize trainer
        trainer = ABSAKFoldTrainer()

        # Load dataset
        df = trainer.load_dataset(data_path)

        # Split into train+validation and test sets
        train_val_df, test_df = train_test_split(
            df,
            test_size=test_split,
            random_state=42,
            stratify=df['label']
        )

        print(f"\nDataset Split:")
        print(f"  Train+Validation: {len(train_val_df)} samples")
        print(f"  Test (holdout): {len(test_df)} samples")

        # Perform K-Fold cross-validation
        results_df = trainer.cross_validate(
            df=train_val_df,
            k=k_folds,
            output_dir=output_dir,
            epochs=epochs,
            batch_size=batch_size,
            learning_rate=learning_rate
        )

        # Final test on holdout set
        test_df['sentiment'] = test_df['label'].map(trainer.id2label)

        best_model_path = "/content/kfold_models/best_model.pth"
        accuracy, f1 = trainer.final_test(test_df, best_model_path)

        print("\n" + "=" * 60)
        print("K-FOLD CROSS VALIDATION COMPLETE!")
        print("=" * 60)
        print(f"\nResults saved in: {os.path.abspath(output_dir)}")
        print(f"Each fold saved as: fold_X.pth")
        print(f"Best model saved as SINGLE FILE: {output_dir}/best_model.pth")
        print(f"Final test accuracy: {accuracy:.4f}")

    except Exception as e:
        print(f"Error: {str(e)}")
        import traceback
        traceback.print_exc()
        sys.exit(1)

# Run it directly
main()

ABSA Model K-Fold Cross Validation
============================================================
Loading base model: yangheng/deberta-v3-base-absa-v1.1
Base model loaded
Loading dataset from: /content/AI-Product-Review-Analyzer/train_dataset.csv
Loaded 809 samples
Sentiment distribution:
   negative: 362 (44.7%)
   neutral: 93 (11.5%)
   positive: 354 (43.8%)

Dataset Split:
  Train+Validation: 647 samples
  Test (holdout): 162 samples

 Starting 5-Fold Cross Validation
============================================================

 Training Fold 1
----------------------------------------

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 2, 'bos_token_id': 1}.

   Training samples: 517
   Validation samples: 130

   Saved fold model to: kfold_models/fold_1.pth

 Fold 1 Results:
   train_loss: 0.1314
   eval_loss: 0.3517
   accuracy: 0.9462
   f1: 0.9235
   precision: 0.9401
   recall: 0.9100

 Training Fold 2
----------------------------------------

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 2, 'bos_token_id': 1}.

   Training samples: 517
   Validation samples: 130

   Saved fold model to: kfold_models/fold_2.pth

 Fold 2 Results:
   train_loss: 0.1128
   eval_loss: 0.3388
   accuracy: 0.9538
   f1: 0.9324
   precision: 0.9325
   recall: 0.9324

 Training Fold 3
----------------------------------------

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 2, 'bos_token_id': 1}.

   Training samples: 518
   Validation samples: 129

Traceback (most recent call last):
  File "/tmp/ipython-input-2365382513.py", line 36, in main
    results_df = trainer.cross_validate(
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ipython-input-638075588.py", line 223, in cross_validate
    fold_result = self.train_fold(
                  ^^^^^^^^^^^^^^^^
  File "/tmp/ipython-input-638075588.py", line 173, in train_fold
    train_result = trainer.train()
                   ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/trainer.py", line 2325, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/trainer.py", line 2674, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/trainer.py", line 4020, in training_step
    loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/trainer.py", line 4110, in compute_loss
    outputs = model(**inputs)
              ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/models/deberta_v2/modeling_deberta_v2.py", line 1077, in forward
    outputs = self.deberta(
              ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/models/deberta_v2/modeling_deberta_v2.py", line 784, in forward
    encoder_outputs = self.encoder(
                      ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/models/deberta_v2/modeling_deberta_v2.py", line 657, in forward
    output_states, attn_weights = layer_module(
                                  ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/modeling_layers.py", line 94, in __call__
    return super().__call__(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/models/deberta_v2/modeling_deberta_v2.py", line 436, in forward
    attention_output, att_matrix = self.attention(
                                   ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/models/deberta_v2/modeling_deberta_v2.py", line 369, in forward
    self_output, att_matrix = self.self(
                              ^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/models/deberta_v2/modeling_deberta_v2.py", line 250, in forward
    rel_att = self.disentangled_attention_bias(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/models/deberta_v2/modeling_deberta_v2.py", line 328, in disentangled_attention_bias
    score += c2p_att / scale.to(dtype=c2p_att.dtype)
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 96.00 MiB. GPU 0 has a total capacity of 14.74 GiB of which 22.12 MiB is free. Process 3243 has 14.72 GiB memory in use. Of the allocated memory 14.42 GiB is allocated by PyTorch, and 166.45 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

Error: CUDA out of memory. Tried to allocate 96.00 MiB. GPU 0 has a total capacity of 14.74 GiB of which 22.12 MiB is free. Process 3243 has 14.72 GiB memory in use. Of the allocated memory 14.42 GiB is allocated by PyTorch, and 166.45 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Traceback (most recent call last):
  File "/tmp/ipython-input-2365382513.py", line 36, in main
    results_df = trainer.cross_validate(
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ipython-input-638075588.py", line 223, in cross_validate
    fold_result = self.train_fold(
                  ^^^^^^^^^^^^^^^^
  File "/tmp/ipython-input-638075588.py", line 173, in train_fold
    train_result = trainer.train()
                   ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/trainer.py", line 2325, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/trainer.py", line 2674, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/trainer.py", line 4020, in training_step
    loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/trainer.py", line 4110, in compute_loss
    outputs = model(**inputs)
              ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/models/deberta_v2/modeling_deberta_v2.py", line 1077, in forward
    outputs = self.deberta(
              ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/models/deberta_v2/modeling_deberta_v2.py", line 784, in forward
    encoder_outputs = self.encoder(
                      ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/models/deberta_v2/modeling_deberta_v2.py", line 657, in forward
    output_states, attn_weights = layer_module(
                                  ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/modeling_layers.py", line 94, in __call__
    return super().__call__(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/models/deberta_v2/modeling_deberta_v2.py", line 436, in forward
    attention_output, att_matrix = self.attention(
                                   ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/models/deberta_v2/modeling_deberta_v2.py", line 369, in forward
    self_output, att_matrix = self.self(
                              ^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/models/deberta_v2/modeling_deberta_v2.py", line 250, in forward
    rel_att = self.disentangled_attention_bias(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/models/deberta_v2/modeling_deberta_v2.py", line 328, in disentangled_attention_bias
    score += c2p_att / scale.to(dtype=c2p_att.dtype)
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 96.00 MiB. GPU 0 has a total capacity of 14.74 GiB of which 22.12 MiB is free. Process 3243 has 14.72 GiB memory in use. Of the allocated memory 14.42 GiB is allocated by PyTorch, and 166.45 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipython-input-2365382513.py", line 66, in <cell line: 0>
    main()
  File "/tmp/ipython-input-2365382513.py", line 63, in main
    sys.exit(1)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/ultratb.py", line 1101, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/ultratb.py", line 248, in wrapped
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/ultratb.py", line 281, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/inspect.py", line 1769, in getinnerframes
    traceback_info = getframeinfo(tb, context)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/inspect.py", line 1701, in getframeinfo
    lineno = frame.f_lineno
             ^^^^^^^^^^^^^^
AttributeError: 'tuple' object has no attribute 'f_lineno'

TypeError: object of type 'NoneType' has no len()